name: AutoDeploy
main: fun.kaituo.AutoDeploy
version: 1.0
api-version: 1.18
authors: [MinazukiiChocola,YFshadaow]
permissions:
  autodeploy.notify:
    description: Players with this node will be notified for plugin reload
    default: op